apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-crud-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: python-crud-app
  template:
    metadata:
      labels:
        app: python-crud-app
    spec:
      containers:
      - name: python-crud-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 8000
