apiVersion: v1
kind: Service
metadata:
  name: python-crud-app
spec:
  type: {{ .Values.service.type }}
  selector:
    app: python-crud-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
